version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      # Docker images for node
      - image: circleci/node:10.15.3
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      # Install all needed dependencies
      - run:
          name: Installing npm dependencies
          command: npm install
      # Run app commandss
      - run:
          name: Running app tests
          command: npm test
      - run:        
          name: Listing The Project Components
          command: ls -l
      
      - run:        
          name: Attributing Rigths
          command: sudo chmod +x /home/circleci/repo/smcli.js
      
      - run:        
          name: Testing Project Creation
          command: pwd
          
      # Save the cache for faster builds
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # Save test coverage results
      - store_artifacts:
          path: coverage
          prefix: coverage
workflows:
  version: 2
  develop:
    jobs:
      - build:
          filters:
            branches:
              only: dev       # only run builds when a push on master branch happens

